#!/bin/bash
# Docker entrypoint script for Ship container
# This script runs as root to fix workspace permissions,
# injects built-in skills into the shared workspace, then starts the application.

set -e

quote_shell_value() {
    local value="$1"
    value=${value//\'/\'\\\'\'}
    printf "'%s'" "$value"
}

# Generate environment variables file for shell/python execution.
# Always rewrite the file to avoid stale env from a reused workspace.
mkdir -p /workspace
echo "# Auto-generated by Ship from runtime environment" > /workspace/.bay_env.sh

# Propagate container-level proxy vars into shell/python user processes.
for name in HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY http_proxy https_proxy all_proxy no_proxy; do
    value="${!name}"
    if [ -n "$value" ]; then
        printf 'export %s=' "$name" >> /workspace/.bay_env.sh
        quote_shell_value "$value" >> /workspace/.bay_env.sh
        printf '\n' >> /workspace/.bay_env.sh
    fi
done

# Split by colon and export each variable
if [ -n "$BAY_PROFILE_ENV" ]; then
    IFS=':' read -ra ENV_PAIRS <<< "$BAY_PROFILE_ENV"
    for pair in "${ENV_PAIRS[@]}"; do
        # Only export if it contains an equals sign and isn't empty
        if [[ "$pair" == *"="* ]]; then
            key="${pair%%=*}"
            value="${pair#*=}"
            printf 'export %s=' "$key" >> /workspace/.bay_env.sh
            quote_shell_value "$value" >> /workspace/.bay_env.sh
            printf '\n' >> /workspace/.bay_env.sh
        fi
    done
fi

chown shipyard:shipyard /workspace/.bay_env.sh
chmod 644 /workspace/.bay_env.sh
echo "[ship] generated /workspace/.bay_env.sh from runtime env"

# Fix workspace permissions for shipyard user
# This is needed when /workspace is a mounted volume with root ownership
if [ -d /workspace ]; then
    chown -R shipyard:shipyard /workspace 2>/dev/null || true
    chmod 755 /workspace 2>/dev/null || true
fi

# Inject built-in skills into /workspace/skills/ (per-skill overwrite).
# Each skill directory in /app/skills/ is individually rm+cp'd so that:
#   - built-in skills are always at the image version (idempotent)
#   - skills from other runtimes (Gull) or upper-layer agents are untouched
if [ -d /app/skills ] && [ "$(ls -A /app/skills 2>/dev/null)" ]; then
    mkdir -p /workspace/skills
    for skill_dir in /app/skills/*/; do
        [ -d "$skill_dir" ] || continue
        skill_name=$(basename "$skill_dir")
        rm -rf "/workspace/skills/$skill_name"
        cp -r "$skill_dir" "/workspace/skills/$skill_name"
    done
    chown -R shipyard:shipyard /workspace/skills
    echo "[ship] injected built-in skills to /workspace/skills/"
fi

# Execute the main command
exec "$@"
